services:
  - type: web
    name: agentic-ai-bootcamp
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.16.0
      - key: NEXT_PUBLIC_CONTACT_ENDPOINT
        sync: false
    autoDeploy: true
